### ISSUE TITLE
Error on Activation

### ISSUE THREAD

**Issue by davidshq** [jtsternberg/GC-Staff#1]
Activation of the plugin failed with the following error:

"Warning: require(vendor/autoload_52.php): failed to open stream: No such file or directory in /home/liquidc4/staging/1/wp-content/plugins/GC-Staff-master/gc-staff.php on line 38

Fatal error: require(): Failed opening required 'vendor/autoload_52.php' (include_path='.:/usr/local/php56/pear') in /home/liquidc4/staging/1/wp-content/plugins/GC-Staff-master/gc-staff.php on line 38"

**Comment by jtsternberg** [comment]
Be sure to use the zip file in the repo: https://github.com/jtsternberg/GC-Staff/raw/master/gc-staff.zip

**Comment by davidshq** [comment]
That was the issue, thanks!
