### ISSUE TITLE
404 on View

### ISSUE THREAD

**Issue by davidshq** [jtsternberg/GC-Staff#2]
I successfully setup the plugin.

I added an individual and created a staff position for them.

Published the profile.

When I click on the permalink I get a 404 message.

(This is low priority for me personally, I'm just playing around with it)

**Comment by jtsternberg** [comment]
You probably need to flush your permalinks. This commit SHOULD fix it for the future: https://github.com/jtsternberg/GC-Staff/commit/fae4040f38e26491a23bc327a53f3e54dfa84c56

**Comment by davidshq** [comment]
You were right, I flushed the permalinks and it started working.
